name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Get committed files
        id: commitData
        run: |
          committed_files="$(git diff --name-status HEAD^ HEAD)"
          committed_files_json=$(jq -n --argjson array "$committed_files" '$array')
          node_response="$(node ../scripts/knapsack2amplience.js committed_files_json)"
          echo "Node response: ${node_response}"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
