name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Show committed files
        run: |
          git diff --name-status HEAD^ HEAD
      - name: Echo committed files
        run: |
          echo "$(git diff --name-status HEAD^ HEAD)"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
