name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Get committed files
        id: commitData
        run: |
          committedFiles="$(git diff --name-status HEAD^ HEAD)"
          echo "committedFiles length is: ${#committedFiles[@]}"
          for committedFile in ${committedFiles}; do
            fileData=(${committedFiles//\\t/ })
            echo "file name: ${fileData[1]}"
            echo "commit type: ${fileData[0]}"
          done
      - run: echo "ğŸ This job's status is ${{ job.status }}."
