name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [pull_request]
jobs:
  convert_knapsack_json_to_amplience:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Get committed files
        id: commitData
        run: |
          committed_files="$(git diff --name-status HEAD^ HEAD)"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Running script
        run: npm run patrick
        id: get_output
      - name: Get output value
        run: echo "The output value is ${{ steps.get_output.outputs.my_output }}"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
