name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Get committed files
        id: commitData
        run: |
          echo "committedFiles=(${git diff --name-status HEAD^ HEAD})" >> $GITHUB_OUTPUT
          for committedFile in committedFiles; do
            fileData=(${committedFile//\t/ });
            echo "file name: $fileData[1]" >> $GITHUB_OUTPUT
            echo "commit type: $fileData[0]" >> $GITHUB_OUTPUT
      - run: echo "ğŸ This job's status is ${{ job.status }}."
